travis:
  secure:
    BINSTAR_TOKEN: UOUoJ+UeLdgN0vQmd2n0IQfu/untERSarNbPiV1jOcFFbBQcCRnNCasJiGmQJgNjjAQQOGkWWoCKdryQqzsbxgNWd5Ws525yV46bQSHXmHSkvXvJ5pC1Yxun/jj7a38I55RzSpCo0zepeUUbDtj9SMwwTEDTCn/cR543ENpdu5EkgW3B9jS+iYNvxMdCekHisCkeHB1G80PzuwiC/DwZr6WQuOGP014rhCT5JNcEEC4zklDig4p8d4bvaecwt/Ge//VnNXoIxWqw2qyrrixQv7Ss44l/NfBo2ztqQPmhIHelC/Av6zp7fJQuOMcP/xzsmuuN7DJ1iz0DWGnylNPBemDt2epKp4WEtp3P7SB9XWBsbEmWjgMAxzlIaNasJKdz22fpSlUDKBbZDFEFrafwJ1aXFRe1iAb3vvxXHgBf+iLlGNXsMAWpGS/o91TFgK0oE+WjsppgKVTX429gkeCGVmZyb7rEc411w/UwRHpNaIexYyM2o9Csovck/3dMI/eBM5KVbC99S0NWAYbSTl3z0fS9fT2nf1+2GwRes1cRJdGvlyk9AK9F3Ya0VAQHt1+L/1z6qx1ipfZDAhxerNr9FxjQCOIoJ7XChkGzL319W5nLV2Hd2jpvxD6shZwemrkks0Z3Gp7YQy7mV6IiMSBLsULIbl9RlhKP8Acu/1Y78rA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
