appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Vowhq+yBZGEwjsTEoiewCrdz+JqgYvjzsEH2uLGOoybvXmBV3fEsArVGBg/3eB+lWjttReAaissUZe+YUgqVqoRrFWsKh6b0cw6T0Gu/BRM448CzwCUWKHVh14UlsqDHCoum7Q+UEv0acEhecX5Qjpe+P6i6B9jtdBsu9WzPRfNonYuMkr2kkWr0ENQ/x3NIiYkSvaGrsirCliurrunc78lBPFSVJFZfdjBqQGgwWj3+vM+4435MOyQIBMQ6v2fnC+ybg1SHz14H0qhnykCzombHimKr77sgKqIHuJF1lpwAmvONVCPmqP+GmwxBIEcMPNHPXcV2yyvg46ZbW9KMTZ4NlYzDRO623dp79Ck3TICN5LhMqit0mZz+Glgl6nB1zJeSpUnQM5xo+BatBh8nX2Cc7oO6GIYNR4wZ4gT5WpVz7IT0tB/EJkSL7fbK8fYvPrUw57S7eIthZXSFLCllIHBLt6LtiBm67oW/Q9MpLEoYCeIvTIwdcagBrR9p9V+Ul03TznOYZQUITtlH3gJc/hBKnTb3GqXn+b6RWJAkWFGPTtsF7m6ygnXPOEjIV5WJm9BfelR0WzMXlmnuGl6uQ6fbpAEzb61ByAzbVbhJZ+tHq88mu7ZAmusuUq/ehnmbM6GVj+rSDKYTj+vM61+HJZQJKsL/RyoOf5+QuGQPiYA=}
conda_forge_output_validation: true
